import fs from 'node:fs';
import path from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { config } from '../config/index.js';
import { badRequest, forbidden } from './errors.js';

/**
 * Uploaded-file safety.  A filename extension is a *claim*, not a fact, so the content
 * itself is inspected (magic bytes) and must agree with the claim before the file is
 * written; the stored name is generated by us, so user data never reaches the filesystem
 * as a path.  Files are served only through an authenticated, ownership-checked API
 * route — never as a static directory.
 */

const SIGNATURES = [
  {
    mime: 'image/jpeg',
    label: 'JPEG image',
    exts: ['.jpg', '.jpeg'],
    test: (b) => b.length > 3 && b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff,
  },
  {
    mime: 'image/png',
    label: 'PNG image',
    exts: ['.png'],
    test: (b) => b.length > 8 && b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e && b[3] === 0x47
      && b[4] === 0x0d && b[5] === 0x0a && b[6] === 0x1a && b[7] === 0x0a,
  },
  {
    mime: 'image/gif',
    label: 'GIF image',
    exts: ['.gif'],
    test: (b) => b.length > 6 && b.subarray(0, 3).toString('latin1') === 'GIF' && b[3] === 0x38,
  },
  {
    mime: 'image/webp',
    label: 'WebP image',
    exts: ['.webp'],
    test: (b) => b.length > 12 && b.subarray(0, 4).toString('latin1') === 'RIFF'
      && b.subarray(8, 12).toString('latin1') === 'WEBP',
  },
  {
    mime: 'application/pdf',
    label: 'PDF document',
    exts: ['.pdf'],
    test: (b) => b.length > 5 && b.subarray(0, 5).toString('latin1') === '%PDF-',
  },
  {
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    label: 'DOCX (zip container)',
    exts: ['.docx'],
    test: (b) => b.length > 4 && b[0] === 0x50 && b[1] === 0x4b && b[2] === 0x03 && b[3] === 0x04,
  },
  {
    mime: 'text/plain',
    label: 'plain text',
    exts: ['.txt', '.csv'],
    test: (b) => {
      for (const byte of b.subarray(0, 4096)) {
        // NUL or control bytes other than tab/LF/CR ⇒ not text we are willing to serve
        if (byte === 0 || (byte < 32 && byte !== 9 && byte !== 10 && byte !== 13)) return false;
      }
      return b.length > 0;
    },
  },
];

const IMAGE_MIMES = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/gif']);

/** Which kinds of attachment may hold which content — a photo field must not become a .zip. */
export const KIND_POLICY = {
  photo: IMAGE_MIMES,
  before_photo: IMAGE_MIMES,
  after_photo: IMAGE_MIMES,
  manual: new Set(['application/pdf', 'image/jpeg', 'image/png']),
  certificate: new Set(['application/pdf', 'image/jpeg', 'image/png']),
  document: new Set(['application/pdf', 'text/plain',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document']),
  qr_label: new Set(['image/png']),
};

/** `../../etc/passwd`, `C:\Windows\x.exe`, newlines in names — all reduced to a safe label. */
export function sanitizeFilename(name) {
  const base = path.basename(String(name ?? 'file').replace(/\\/g, '/'))
    .replace(/[\u0000-\u001f\u007f]/g, '')
    .replace(/[^\w.\- ()\[\],+]/g, '_')
    .replace(/^\.+/, '')
    .slice(0, 140);
  return base || 'file';
}

export function extensionOf(name) {
  return path.extname(String(name ?? '')).toLowerCase();
}

/**
 * @returns {{mime:string, label:string}} the detected type
 * @throws {AppError} 400 when the bytes match nothing we accept or contradict the extension
 */
export function sniff(buffer, claimedName, kind = 'photo') {
  if (!Buffer.isBuffer(buffer) || buffer.length === 0) throw badRequest('Uploaded file is empty');
  if (buffer.length > config.uploads.maxFileBytes) {
    throw badRequest(`File is larger than ${Math.round(config.uploads.maxFileBytes / 1024 / 1024)} MB`);
  }
  const ext = extensionOf(claimedName);
  if (!config.uploads.allowedExt.includes(ext)) {
    throw forbidden(`File type ${ext || '(none)'} is not allowed. Allowed: ${config.uploads.allowedExt.join(', ')}`);
  }
  const match = SIGNATURES.find((s) => s.test(buffer) && s.exts.includes(ext));
  if (!match) {
    // Extension is on the allow-list but the bytes disagree → almost certainly a disguised file.
    throw badRequest(
      'The file content does not match its extension. Please attach an unmodified photo or document.',
    );
  }
  const allowed = KIND_POLICY[kind];
  if (allowed && !allowed.has(match.mime)) {
    throw badRequest(`A "${kind}" attachment must be one of: ${[...allowed].join(', ')}`);
  }
  if (!config.uploads.allowedMime.includes(match.mime) && match.mime !== 'text/plain') {
    throw forbidden(`Content type ${match.mime} is not enabled on this server`);
  }
  return { mime: match.mime, label: match.label };
}

const uploadsRoot = () => {
  fs.mkdirSync(config.paths.uploads, { recursive: true });
  return path.resolve(config.paths.uploads);
};

/** Writes the buffer under uploads/<YYYY-MM>/<uuid>.<ext>; returns the relative stored name. */
export function store(buffer, ext) {
  const root = uploadsRoot();
  const month = new Date().toISOString().slice(0, 7);
  const dir = path.join(root, month);
  fs.mkdirSync(dir, { recursive: true });
  const safeExt = /^[.a-z0-9]{1,10}$/.test(ext) ? ext : '.bin';
  const storedName = path.posix.join(month, `${randomUUID()}${safeExt}`);
  fs.writeFileSync(path.join(dir, `${path.basename(storedName)}`), buffer, { flag: 'wx' });
  return storedName;
}

/** Resolves a stored name, refusing anything that escapes the uploads root. */
export function resolveStored(storedName) {
  const root = uploadsRoot();
  const abs = path.resolve(root, String(storedName));
  if (abs !== root && !abs.startsWith(root + path.sep)) throw forbidden('Unsafe attachment path');
  return abs;
}

export function removeStored(storedName) {
  try {
    fs.unlinkSync(resolveStored(storedName));
    return true;
  } catch {
    return false; // already gone: deletion of the DB row is what matters
  }
}

export const checksum = (buffer) => createHash('sha256').update(buffer).digest('hex');

export function byteLength(buffer) {
  return Buffer.isBuffer(buffer) ? buffer.length : 0;
}

export function ensureUploadDirs() {
  fs.mkdirSync(config.paths.uploads, { recursive: true });
  fs.mkdirSync(path.dirname(config.paths.database), { recursive: true });
}
